# -- coding: utf-8 --
"""org.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKwuHYC47Q6LUWxTjHEH4GCFBHi5fTdB
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")